name: ROS

on:
  push:
    branches: [melodic]
  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest
    container: athackst/ros1:melodic-dev
    steps:
      - uses: actions/checkout@v2
      - name: "Get workspace"
        run: |
          if [ -f src/ros.repos ]; then
            vcs import --skip-existing < src/ros1.repos src
          fi
      - name: "Get dependencies"
        run: |
          sudo apt-get update
          rosdep update
          rosdep install --from-paths src --ignore-src -y --rosdistro=melodic
      - name: "Build"
        run: |
          colcon build --cmake-args '-DCMAKE_BUILD_TYPE=RelWithDebInfo' -Wall -Wextra -Wpedantic
        continue-on-error: true
      - name: "Test"
        run: |
          colcon test
